sudo: false
language: node_js
node_js:
- '0.10'
script:
- cd webapp && npm install && npm test && npm run build
notifications:
  webhooks: http://deploy.holderdeord.no/travis
  hipchat:
    rooms:
      secure: KtzDTt1HzBZSWIHiEYspGF7TdXPSwyOuyxSn4DZA+E/4c/tVCYOw7N+egBzwkHLU6B/1tTlaXEkv8deOVsiG63fM+f7xvIbbRhQ/flJfZzDBGfySVnuPCg0QafcedKoizBujc0rXolG52Rcs7pVGqK4NEPHGv8BbLo7g7esTrY8=
